config/routes.rb
MyBlog::Application.routes.draw do
  devise_for :admins, skip: :registrations

  root to: "posts#index"
  resources :posts do
    get :markdown_code
  end
  resources :tags, :only => [:index, :show]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags
  attr_accessible :tag_tokens, :title, :body
  attr_reader :tag_tokens
  
  validates_presence_of :title, :body
  markdownize! :body

  scope :recent, -> { order("created_at DESC").limit(10) }

  def summary(max_length=300)
    rendered_body.gsub(/(<[^>]*>)|\n|\t/s," ")[0..max_length] + "..."
  end
  
  def published_at
    created_at.strftime("Published at %l:%M%p on %m/%d/%y")
  end
  
  def tag_tokens=(ids)
    self.tag_ids = ids.split(",").map(&:to_i).delete_if { |i| i == 0 }
  end
  
  def tag_tokens
    tag_ids
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]

  def index
    @posts = Post.recent
    respond_to do |format|
      format.html
      format.rss { render layout: false }
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post created" }
      else
        format.html { render action: :edit, notice: "Try again" }
      end
    end
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: "Post upated" }
      else
        format.html { render action: :edit }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_path, notice: "Post removed"}
    end
  end

  def markdown_code
    @formatted_code = CodeRay.scan(params[:data]["code"], params[:data]["language"].to_sym).div
    respond_to do |format|
      format.json { render json: @formatted_code.to_json }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    params[:q].gsub!(/create_(.+?)_end/) do
      Tag.create!(name: $1).id
    end
    @tags = Tag.where("name like ?", "%#{params[:q]}%")
    respond_to do |format|
      format.json { render :json => @tags.map(&:attributes) }
    end
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_sidebar.slim
h2 About Me
p Ruby on Rails developer and instructor for Big Nerd Ranch.
.divider
  a.btn.btn-info href="#{posts_url(:rss)}"
    i.icon-th-list     
    '   RSS Feed
h2 Tags
ul.unstyled
  - Tag.all.each do |tag|
    li = link_to "#{tag.name} (#{tag.posts.count})", tag_path(tag)

app/views/layouts/application.slim
doctype html
html
head
  title Coded World
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
body
  .navbar.navbar-fixed-top
    .navbar-inner#header
      .container
        a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        =link_to "greggroth: Coded World", root_url, {class: :brand}
        .nav-collapse
          ul.nav
            li = link_to "Github", "https://github.com/greggroth"
            li = link_to "LinkedIn", "http://www.linkedin.com/pub/greggory-rothmeier/3a/82/5aa" 
            li = link_to "Twitter", "https://twitter.com/#!/greggroth"
            li = link_to "ATLBeerList", "http://www.atlbeerlist.com"
            li = link_to "My Wolfram Demonstrations", "http://demonstrations.wolfram.com/author.html?author=Greggory%20Rothmeier"
  .container
    - if flash[:alert]
      .row
        .span6.offset3
          .alert.alert-error
            a.close data-dismiss="alert" &times;
            = flash[:alert]
    - if flash[:notice]
      .row
        .span6.offset3
          .alert.alert-info
            a.close data-dismiss="alert" &times;
            = flash[:notice]
    .row
      .span10
        == yield
      .span2
        = render partial: "layouts/sidebar"
    footer.footer
      p Site styling provided by #{link_to "Twitter Bootstrap", "http://twitter.github.com/bootstrap/index.html"}.
      - if admin_signed_in?
        p #{link_to "Logout", destroy_admin_session_path, method: :delete} | #{link_to "New Post", new_post_path}
      - else
        p = link_to "Admin login", new_admin_session_path

app/views/posts/_form.slim
= semantic_form_for @post, :html => {:class => "well"} do |f|
  - if @post.errors.any?
    .row
      .span6.offset1
        .alert.alert-error
          | Houston we have some issues:
          ul
            - @post.errors.full_messages.each do |msg|
              li = msg

  = f.inputs do
    = f.input :title, input_html: { class: "span6"}
    = f.input :tag_tokens, input_html: { id: "post_tags_tokens", "data-pre" => @post.tags.map(&:attributes).to_json }
    = f.input :body,  :input_html => { id: "post-body", class: "span8"}, wrapper_html: { class: "control-label wmd-input", id: "wmd-input" }
    .form-actions
      = f.submit "Submit", class: "btn btn-primary"
      = link_to "Cancel", @post, class: "btn btn-cancel"
br
h3 Preview
div.well#post-preview

app/views/posts/edit.slim
h1 Edit post
== render 'form'

app/views/posts/index.slim
h1 Welcome!
- @posts.each do |post|
  .post_summary
    h2 = link_to post.title, post
    p.published_at = post.published_at
    p = post.summary

app/views/posts/new.slim
h1 Create post
== render 'form'

app/views/posts/show.slim
#fb-root
javascript:
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

h1 = @post.title
p.published_at = @post.published_at
- unless @post.tags.empty?
  .tags
    | Tags: 
    - @post.tags.each do |i|
      = link_to i.name, i, class: "btn-tag"
.post-body
  == @post.rendered_body
.fb-comments data-href='#{post_url(@post)}' data-num-posts="2" data-width="470"
- if admin_signed_in?
  div.modify_links
    #{link_to "edit", edit_post_path(@post)}  |  #{link_to "remove", @post, method: :delete}
  

app/views/tags/show.slim
h1 Posts tagged with "#{@tag.name}"
- @tag.posts.each do |post|
  .post_summary
    h2 = link_to post.title, post
    p.published_at = post.published_at
    - unless post.tags.empty?
      .tags
        | Tags: 
        - post.tags.each do |i|
          = link_to i.name, i, class: "btn-tag"
    p = post.summary